"""add simulator config + runs

Revision ID: 23897f2754ef
Revises: b212b722c638
Create Date: 2026-01-19 10:36:26.663166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23897f2754ef'
down_revision: Union[str, Sequence[str], None] = 'b212b722c638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulator_configs',
    sa.Column("id", sa.String(length=36), primary_key=True),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.String(length=40), nullable=False),
    sa.Column('avg_events_per_day', sa.Integer(), nullable=False),
    sa.Column('typical_ticket_cents', sa.Integer(), nullable=False),
    sa.Column('payroll_every_n_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('simulator_runs',
    sa.Column("id", sa.String(length=36), primary_key=True),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulator_runs')
    op.drop_table('simulator_configs')
    # ### end Alembic commands ###
