"""business onboarding + integration

Revision ID: 4dcd18d89865
Revises: 334aec1211d3
Create Date: 2026-01-26 21:16:30.685844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dcd18d89865'
down_revision: Union[str, Sequence[str], None] = '334aec1211d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulator_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulator_configs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('profile', sa.VARCHAR(length=40), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=False),
    sa.Column('avg_events_per_day', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False),
    sa.Column('typical_ticket_cents', sa.INTEGER(), server_default=sa.text('6500'), autoincrement=False, nullable=False),
    sa.Column('payroll_every_n_days', sa.INTEGER(), server_default=sa.text('14'), autoincrement=False, nullable=False),
    sa.Column('next_emit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_emit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('max_backfill_events', sa.INTEGER(), server_default=sa.text('2000'), autoincrement=False, nullable=False),
    sa.Column('seed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lock_owner', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('lock_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('simulator_configs_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('simulator_configs_pkey')),
    sa.UniqueConstraint('business_id', name=op.f('simulator_configs_business_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
