"""add business integration profile

Revision ID: 4f2f595d87a6
Revises: 23897f2754ef
Create Date: 2026-01-23 21:12:21.063868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2f595d87a6'
down_revision: Union[str, Sequence[str], None] = '23897f2754ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_integration_profiles',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('bank', sa.Boolean(), nullable=False),
    sa.Column('payroll', sa.Boolean(), nullable=False),
    sa.Column('card_processor', sa.Boolean(), nullable=False),
    sa.Column('ecommerce', sa.Boolean(), nullable=False),
    sa.Column('invoicing', sa.Boolean(), nullable=False),
    sa.Column('simulation_params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_integration_profiles')
    # ### end Alembic commands ###
