"""add simulator tables

Revision ID: 5ac69564ef38
Revises: 560c44009fe2
Create Date: 2026-01-27 08:24:09.411317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac69564ef38'
down_revision: Union[str, Sequence[str], None] = '560c44009fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create simulator_runs only if it doesn't already exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema='public'
                  AND table_name='simulator_runs'
            ) THEN
                CREATE TABLE simulator_runs (
                    id VARCHAR(36) NOT NULL,
                    business_id VARCHAR(36) NOT NULL,
                    kind VARCHAR(30) DEFAULT 'manual' NOT NULL,
                    started_at TIMESTAMPTZ NOT NULL,
                    params JSON NOT NULL,
                    PRIMARY KEY (id),
                    CONSTRAINT fk_simulator_runs_business_id
                        FOREIGN KEY (business_id)
                        REFERENCES businesses (id)
                        ON DELETE CASCADE
                );
            END IF;
        END $$;
        """
    )

    # If the migration also creates indexes for simulator_runs, guard those too:
    op.execute("CREATE INDEX IF NOT EXISTS ix_simulator_runs_business_id ON simulator_runs (business_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_simulator_runs_started_at ON simulator_runs (started_at)")

    # ... keep the rest of your migration (other tables/indexes) ...


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulator_runs_business_id'), table_name='simulator_runs')
    op.drop_index('ix_simrun_business_started', table_name='simulator_runs')
    op.drop_table('simulator_runs')
    op.drop_index(op.f('ix_simulator_configs_next_emit_at'), table_name='simulator_configs')
    op.drop_index('ix_simcfg_enabled_nextemit', table_name='simulator_configs')
    op.drop_index('ix_simcfg_business_id', table_name='simulator_configs')
    op.drop_table('simulator_configs')
    # ### end Alembic commands ###
