"""add simulator tables

Revision ID: 5ac69564ef38
Revises: 560c44009fe2
Create Date: 2026-01-27 08:24:09.411317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac69564ef38'
down_revision: Union[str, Sequence[str], None] = '560c44009fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulator_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.String(length=40), nullable=False),
    sa.Column('avg_events_per_day', sa.Integer(), nullable=False),
    sa.Column('typical_ticket_cents', sa.Integer(), nullable=False),
    sa.Column('payroll_every_n_days', sa.Integer(), nullable=False),
    sa.Column('next_emit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_emit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_backfill_events', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('lock_owner', sa.String(length=64), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index('ix_simcfg_business_id', 'simulator_configs', ['business_id'], unique=False)
    op.create_index('ix_simcfg_enabled_nextemit', 'simulator_configs', ['enabled', 'next_emit_at'], unique=False)
    op.create_index(op.f('ix_simulator_configs_next_emit_at'), 'simulator_configs', ['next_emit_at'], unique=False)
    op.create_table('simulator_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simrun_business_started', 'simulator_runs', ['business_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_simulator_runs_business_id'), 'simulator_runs', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulator_runs_business_id'), table_name='simulator_runs')
    op.drop_index('ix_simrun_business_started', table_name='simulator_runs')
    op.drop_table('simulator_runs')
    op.drop_index(op.f('ix_simulator_configs_next_emit_at'), table_name='simulator_configs')
    op.drop_index('ix_simcfg_enabled_nextemit', table_name='simulator_configs')
    op.drop_index('ix_simcfg_business_id', table_name='simulator_configs')
    op.drop_table('simulator_configs')
    # ### end Alembic commands ###
