"""add simulator scheduler fields

Revision ID: 615db3bd80a9
Revises: 1209affeeb8f
Create Date: 2026-01-26 20:28:23.742804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '615db3bd80a9'
down_revision: Union[str, Sequence[str], None] = '1209affeeb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulator_configs')
    op.drop_table('simulator_runs')
    op.create_unique_constraint('uq_business_category_id', 'business_category_map', ['business_id', 'category_id'])
    op.add_column('business_integration_profiles', sa.Column('scenario_id', sa.String(length=80), server_default=sa.text("'restaurant_v1'"), nullable=False))
    op.add_column('business_integration_profiles', sa.Column('story_version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.alter_column('business_integration_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('business_integration_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_business_integration_profiles_scenario_id'), 'business_integration_profiles', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_businesses_org_id'), 'businesses', ['org_id'], unique=False)
    op.drop_constraint(op.f('businesses_org_id_fkey'), 'businesses', type_='foreignkey')
    op.create_foreign_key(None, 'businesses', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.create_foreign_key(op.f('businesses_org_id_fkey'), 'businesses', 'organizations', ['org_id'], ['id'])
    op.drop_index(op.f('ix_businesses_org_id'), table_name='businesses')
    op.drop_index(op.f('ix_business_integration_profiles_scenario_id'), table_name='business_integration_profiles')
    op.alter_column('business_integration_profiles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('business_integration_profiles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('business_integration_profiles', 'story_version')
    op.drop_column('business_integration_profiles', 'scenario_id')
    op.drop_constraint('uq_business_category_id', 'business_category_map', type_='unique')
    op.create_table('simulator_runs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('simulator_runs_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('simulator_runs_pkey'))
    )
    op.create_table('simulator_configs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('avg_events_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typical_ticket_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payroll_every_n_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('simulator_configs_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('simulator_configs_pkey')),
    sa.UniqueConstraint('business_id', name=op.f('simulator_configs_business_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
