"""fix category

Revision ID: cd8e5976333f
Revises: 620795993094
Create Date: 2026-01-25 12:33:16.374602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8e5976333f'
down_revision: Union[str, Sequence[str], None] = '620795993094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_business_id'), 'accounts', ['business_id'], unique=False)
    op.create_index('ix_bcm_business_id', 'business_category_map', ['business_id'], unique=False)
    op.create_index('ix_bcm_category_id', 'business_category_map', ['category_id'], unique=False)
    op.create_index('ix_bcm_system_key', 'business_category_map', ['system_key'], unique=False)
    op.create_index(op.f('ix_business_category_map_business_id'), 'business_category_map', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_category_map_category_id'), 'business_category_map', ['category_id'], unique=False)
    op.create_index(op.f('ix_business_category_map_system_key'), 'business_category_map', ['system_key'], unique=False)
    op.create_index(op.f('ix_categories_account_id'), 'categories', ['account_id'], unique=False)
    op.create_index(op.f('ix_categories_business_id'), 'categories', ['business_id'], unique=False)
    op.create_index(op.f('ix_category_rules_business_id'), 'category_rules', ['business_id'], unique=False)
    op.create_index(op.f('ix_category_rules_category_id'), 'category_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_raw_events_business_id'), 'raw_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_txn_categorizations_business_id'), 'txn_categorizations', ['business_id'], unique=False)
    op.create_index(op.f('ix_txn_categorizations_category_id'), 'txn_categorizations', ['category_id'], unique=False)
    op.create_index('ix_txncat_business_id', 'txn_categorizations', ['business_id'], unique=False)
    op.create_index('ix_txncat_source_event_id', 'txn_categorizations', ['source_event_id'], unique=False)
    op.create_unique_constraint('uq_txncat_business_sourceevent', 'txn_categorizations', ['business_id', 'source_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_txncat_business_sourceevent', 'txn_categorizations', type_='unique')
    op.drop_index('ix_txncat_source_event_id', table_name='txn_categorizations')
    op.drop_index('ix_txncat_business_id', table_name='txn_categorizations')
    op.drop_index(op.f('ix_txn_categorizations_category_id'), table_name='txn_categorizations')
    op.drop_index(op.f('ix_txn_categorizations_business_id'), table_name='txn_categorizations')
    op.drop_index(op.f('ix_raw_events_business_id'), table_name='raw_events')
    op.drop_index(op.f('ix_category_rules_category_id'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_business_id'), table_name='category_rules')
    op.drop_index(op.f('ix_categories_business_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_account_id'), table_name='categories')
    op.drop_index(op.f('ix_business_category_map_system_key'), table_name='business_category_map')
    op.drop_index(op.f('ix_business_category_map_category_id'), table_name='business_category_map')
    op.drop_index(op.f('ix_business_category_map_business_id'), table_name='business_category_map')
    op.drop_index('ix_bcm_system_key', table_name='business_category_map')
    op.drop_index('ix_bcm_category_id', table_name='business_category_map')
    op.drop_index('ix_bcm_business_id', table_name='business_category_map')
    op.drop_index(op.f('ix_accounts_business_id'), table_name='accounts')
    # ### end Alembic commands ###
