from __future__ import annotations

from backend.app.signals.v2_compute import (
    DetectorDefinition,
    DetectorRunResult,
    DetectorRunSummary,
    DetectedSignal,
)
from backend.app.signals.v2_detectors import (
    DETECTOR_DEFINITIONS,
    detect_concentration_expense_top_vendor,
    detect_concentration_revenue_top_customer,
    detect_expense_creep_by_vendor,
    detect_expense_new_recurring,
    detect_expense_spike_vs_baseline,
    detect_hygiene_signal_flapping,
    detect_hygiene_uncategorized_high,
    detect_liquidity_cash_trend_down,
    detect_liquidity_runway_low,
    detect_low_cash_runway,
    detect_revenue_decline_vs_baseline,
    detect_revenue_volatility_spike,
    detect_timing_inflow_outflow_mismatch,
    detect_timing_payroll_rent_cliff,
    detect_unusual_outflow_spike,
    run_v2_detectors,
    run_v2_detectors_with_summary,
)

__all__ = [
    "DetectedSignal",
    "DetectorDefinition",
    "DetectorRunResult",
    "DetectorRunSummary",
    "DETECTOR_DEFINITIONS",
    "detect_concentration_expense_top_vendor",
    "detect_concentration_revenue_top_customer",
    "detect_expense_creep_by_vendor",
    "detect_expense_new_recurring",
    "detect_expense_spike_vs_baseline",
    "detect_hygiene_signal_flapping",
    "detect_hygiene_uncategorized_high",
    "detect_liquidity_cash_trend_down",
    "detect_liquidity_runway_low",
    "detect_low_cash_runway",
    "detect_revenue_decline_vs_baseline",
    "detect_revenue_volatility_spike",
    "detect_timing_inflow_outflow_mismatch",
    "detect_timing_payroll_rent_cliff",
    "detect_unusual_outflow_spike",
    "run_v2_detectors",
    "run_v2_detectors_with_summary",
]
